# Generated by Django 2.1.15 on 2020-03-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='label',
            field=models.TextField(default='unknow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='label2',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
